### ISSUE TITLE
Todo-Eingabe kann nicht validiert werden

### ISSUE THREAD

**Issue by SchoolAccountTom** [Philipp-Aaron-Schmid/324-DevOps#4]
Wer:
- Als Benutzer

Was:
- Möchte ich sicherstellen, dass meine Eingaben für die Aufgaben validiert werden und gültig sind.

Warum:
- Damit keine leeren oder ungültigen Aufgaben hinzugefügt werden.

| Akzeptanzkriterien |
| :--- |
| 1. Beim Hinzufügen einer Aufgabe wird überprüft, ob das Eingabefeld nicht leer ist. |
| 2. Wenn das Eingabefeld leer ist, wird eine Fehlermeldung angezeigt. |
| 3. Die Aufgabe wird nur gespeichert, wenn das Eingabefeld gültigen Text enthält. |
| 4. Die Fehlermeldung verschwindet, wenn gültiger Text eingegeben wird. |

**Tasks:**
 
- [ ] **Inplementieren von validierungs Logik beim Eingeben von Todo Tasks**
- [ ] **Eine Methode entwickeln damit Felder nicht leer gelassen werden können**
- [ ] **Eine Methode entwickeln damit Felder gültigen Text enthalten müssen damit sie speichern**
- [ ] **Eine Methode für Fehlermeldungen entwickeln**
