### ISSUE TITLE
Backend Funktion check

### ISSUE THREAD

**Issue by D3li4** [Philipp-Aaron-Schmid/324-DevOps#8]
### Wer
User

### Was
Der User kann das Backend nicht starten.

### Warum
Um auf einen nicht funktionierenden Teil hinzuweisen.

### Akzeptanzkriterien
1. User kann die Frontend Anwendung starten und über einen Browser erreichen.
2. User kann einen neuen Task erstellen.
3. Nachdem der Task abgeschickt wurde, erscheint die Fehlermeldung, dass keine Antwort vom Backend kommt (Not running).
4. Nach dem Einschalten des Backends verschwindet die Fehlermeldung nach Aktualisierung des Browsers.

### Tasks
- [ ] Backend starten und überprüfen, warum es nicht funktioniert.
- [ ] Sicherstellen, dass das Backend korrekt mit der Frontend-Anwendung kommuniziert.
- [ ] Testen, ob nach dem Starten des Backends die Fehlermeldung bei der Task-Erstellung verschwindet.
- [ ] Benachrichtigen des Teams über den aktuellen Status des Backend-Problems.
